services:
  - type: web
    name: music-app
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn project.wsgi:application --bind 0.0.0.0:$PORT"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: "project.settings"
      - key: PORT
        value: "10000"
      - key: PYTHON_VERSION
        value: "3.10"
